/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatementImporterRouteImport } from './routes/statement-importer'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatementImporterIndexRouteImport } from './routes/statement-importer/index'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as StatementImporterIdRouteImport } from './routes/statement-importer/$id'
import { Route as DeskDoctypeIndexRouteImport } from './routes/desk/$doctype/index'
import { Route as DeskDoctypeNameRouteImport } from './routes/desk/$doctype/$name'

const StatementImporterRoute = StatementImporterRouteImport.update({
  id: '/statement-importer',
  path: '/statement-importer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementImporterIndexRoute = StatementImporterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatementImporterRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const StatementImporterIdRoute = StatementImporterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StatementImporterRoute,
} as any)
const DeskDoctypeIndexRoute = DeskDoctypeIndexRouteImport.update({
  id: '/$doctype/',
  path: '/$doctype/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskDoctypeNameRoute = DeskDoctypeNameRouteImport.update({
  id: '/$doctype/$name',
  path: '/$doctype/$name',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/statement-importer': typeof StatementImporterRouteWithChildren
  '/statement-importer/$id': typeof StatementImporterIdRoute
  '/desk/': typeof DeskIndexRoute
  '/statement-importer/': typeof StatementImporterIndexRoute
  '/desk/$doctype/$name': typeof DeskDoctypeNameRoute
  '/desk/$doctype/': typeof DeskDoctypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/statement-importer/$id': typeof StatementImporterIdRoute
  '/desk': typeof DeskIndexRoute
  '/statement-importer': typeof StatementImporterIndexRoute
  '/desk/$doctype/$name': typeof DeskDoctypeNameRoute
  '/desk/$doctype': typeof DeskDoctypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRouteWithChildren
  '/statement-importer': typeof StatementImporterRouteWithChildren
  '/statement-importer/$id': typeof StatementImporterIdRoute
  '/desk/': typeof DeskIndexRoute
  '/statement-importer/': typeof StatementImporterIndexRoute
  '/desk/$doctype/$name': typeof DeskDoctypeNameRoute
  '/desk/$doctype/': typeof DeskDoctypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/statement-importer'
    | '/statement-importer/$id'
    | '/desk/'
    | '/statement-importer/'
    | '/desk/$doctype/$name'
    | '/desk/$doctype/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/statement-importer/$id'
    | '/desk'
    | '/statement-importer'
    | '/desk/$doctype/$name'
    | '/desk/$doctype'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/statement-importer'
    | '/statement-importer/$id'
    | '/desk/'
    | '/statement-importer/'
    | '/desk/$doctype/$name'
    | '/desk/$doctype/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRouteWithChildren
  StatementImporterRoute: typeof StatementImporterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statement-importer': {
      id: '/statement-importer'
      path: '/statement-importer'
      fullPath: '/statement-importer'
      preLoaderRoute: typeof StatementImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement-importer/': {
      id: '/statement-importer/'
      path: '/'
      fullPath: '/statement-importer/'
      preLoaderRoute: typeof StatementImporterIndexRouteImport
      parentRoute: typeof StatementImporterRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/statement-importer/$id': {
      id: '/statement-importer/$id'
      path: '/$id'
      fullPath: '/statement-importer/$id'
      preLoaderRoute: typeof StatementImporterIdRouteImport
      parentRoute: typeof StatementImporterRoute
    }
    '/desk/$doctype/': {
      id: '/desk/$doctype/'
      path: '/$doctype'
      fullPath: '/desk/$doctype/'
      preLoaderRoute: typeof DeskDoctypeIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/$doctype/$name': {
      id: '/desk/$doctype/$name'
      path: '/$doctype/$name'
      fullPath: '/desk/$doctype/$name'
      preLoaderRoute: typeof DeskDoctypeNameRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskIndexRoute: typeof DeskIndexRoute
  DeskDoctypeNameRoute: typeof DeskDoctypeNameRoute
  DeskDoctypeIndexRoute: typeof DeskDoctypeIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskIndexRoute: DeskIndexRoute,
  DeskDoctypeNameRoute: DeskDoctypeNameRoute,
  DeskDoctypeIndexRoute: DeskDoctypeIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface StatementImporterRouteChildren {
  StatementImporterIdRoute: typeof StatementImporterIdRoute
  StatementImporterIndexRoute: typeof StatementImporterIndexRoute
}

const StatementImporterRouteChildren: StatementImporterRouteChildren = {
  StatementImporterIdRoute: StatementImporterIdRoute,
  StatementImporterIndexRoute: StatementImporterIndexRoute,
}

const StatementImporterRouteWithChildren =
  StatementImporterRoute._addFileChildren(StatementImporterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRouteWithChildren,
  StatementImporterRoute: StatementImporterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
